#!/usr/bin/env bash

set -euo pipefail

# Disable globbing (because Bash is terrible)
set -o noglob

# Default the test scope to all of the specs
SCOPE=${1:-'spec/**/*.js'}

# Run the tests
NODE_ENV=test mocha --timeout 5000 --exit -r @babel/register spec/spec-helper.js $SCOPE
